title: FanLiu's Homepage
page-top-title: FanLiu
top-section-bg-text: Be what you wanna be
home-subtitle: FanLiu&ensp;|&ensp;
copyright-text: "&copy; FanLiu 2023-2025. All Rights Reserved."
site_name: "FanLiu"
site_description: "Medical Image Segmentation"
email: "71265902138@stu.ecnu.edu.cn"
